apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: sock-shop
data:
  config.toml: |
    [kubemonkey]
    run_hour = 8                              # Run scheduling at 8am on weekdays
    start_hour = 10                           # Don't schedule any pod deaths before 10am
    end_hour = 16                             # Don't schedule any pod deaths after 4pm
    blacklisted_namespaces = ["kube-system"]  # Critical apps live here
    whitelisted_namespaces = ["sock-shop"]    # Target Namespace
    time_zone = "Singapore/Singapore"
    graceperiod_sec= 10
    [debug]
    enabled= true
    schedule_immediate_kill= true
